bibliography: references.bib
bibtex_bibfiles: ['references.bib']
bibtex_default_style: 'alpha'
copyright: Copyright CC-BY ©2023 
sphinx:
  config:
    bibtex_reference_style: author_year
#    bibtex_bibfiles: references.bib
jupyter:
  jupytext:
    cell_metadata_filter: -all
    formats: ipynb,md
    text_representation:
      extension: .md
      format_name: markdown
      format_version: '1.3'
      jupytext_version: 1.14.4
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
